### PR TITLE
第一个版本 ts类型

### PR DESCRIPTION
**Pull request by javaswing**
- 添加一个较为完善TS类型，及对应的检测命令`test-typings`与测试用例，并安装对应的ts-node环境
- 修复`example/text.js`中`addEffect`方法添加的动画类型并不存在 `backInBottom`于`effects.js`中的问题
- 其它，有些不确定的类型用了 `todo`进行标记

### CODE REVIEW

**Comment by drawcall** [comment]
Wonderful work

**Comment by drawcall** [comment]
Very careful work, are you interested in creating a video site based on FFCreator+LowCode.

**Comment by javaswing** [comment]
> Very careful work, are you interested in creating a video site based on FFCreator+LowCode.

可以的，个人比较有兴趣

**Comment by drawcall** [comment]
> > Very careful work, are you interested in creating a video site based on FFCreator+LowCode.
> 
> 可以的，个人比较有兴趣

Oh, I have given you the read and write permissions. npm publish, oh I don’t know your account.

**Comment by javaswing** [comment]
> > > Very careful work, are you interested in creating a video site based on FFCreator+LowCode.
> > 
> > 
> > 可以的，个人比较有兴趣
> 
> Oh, I have given you the read and write permissions. npm publish, oh I don’t know your account.

my npm account username  `java_swing`

**Pull request merged**
